# Generated by Django 2.1 on 2021-05-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0008_auto_20210517_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='tipo_pago',
            field=models.IntegerField(choices=[(0, 'Contado'), (1, 'Credito')], default=0),
        ),
    ]
