# Generated by Django 2.1 on 2021-05-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0009_caso_tipo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='audiencia',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='formadepago',
            name='tipo',
        ),
        migrations.AddField(
            model_name='formadepago',
            name='fecha_fin_credito',
            field=models.DateField(null=True),
        ),
    ]
